name: EDuke32

on:
  push:
    paths:
      - 'homebrew/EDuke32/**'
  pull_request:
    paths:
      - 'homebrew/EDuke32/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install bash clang-18 lld-18
        sudo apt install build-essential cmake pkg-config libarchive-tools

    - name: Install toolchain
      run: |
        wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
        sudo tar xf ps5-payload-dev.tar.gz -C /

    - name: Build
      run: |
        PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/EDuke32/build.sh

    - name: Install HD pack
      run: |
        ./homebrew/EDuke32/hdpack.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: EDuke32
        path: ./homebrew/EDuke32
        if-no-files-found: error

