name: Payload

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Install toolchain
      run: |
        wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
        sudo tar xf ps5-payload-dev.tar.gz -C /

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        make clean all

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: ./websrv.elf
        if-no-files-found: error

    - name: Upload Launcher
      uses: actions/upload-artifact@v4
      with:
        name: Launcher
        path: ./homebrew/IV9999-FAKE00000_00-HOMEBREWLOADER01.pkg
        if-no-files-found: error
