name: Payload

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout SDK
      uses: actions/checkout@v3
      with:
        repository: ps5-payload-dev/sdk
        path: sdk

    - name: Setup SDK
      working-directory: sdk
      run: |
        sudo apt update
        sudo apt install xxd clang-15 lld-15
        make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk clean install
        echo PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        bash libmicrohttpd.sh
        make clean all

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: ./websrv.elf
        if-no-files-found: error

    - name: Upload Launcher
      uses: actions/upload-artifact@v4
      with:
        name: Launcher
        path: ./homebrew/IV9999-FAKE00000_00-HOMEBREWLOADER01.pkg
        if-no-files-found: error
