name: PKGInstall

on:
  push:
    paths:
      - 'homebrew/PKGInstall/**'
  pull_request:
    paths:
      - 'homebrew/PKGInstall/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install bash clang-15 lld-15
        sudo apt install build-essential

    - name: Install toolchain
      run: |
        wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
        sudo tar xf ps5-payload-dev.tar.gz -C /

    - name: Build
      run: |
        PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: PKGInstall
        path: ./homebrew/PKGInstall
        if-no-files-found: error

